apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nfs
  namespace: nfs
spec:
  serviceName: nfs
  replicas: 1
  selector:
    matchLabels:
      app: nfs
  template:
    metadata:
      labels:
        app: nfs
    spec:
      containers:
        - name: nfs-server
          image: itsthenetwork/nfs-server-alpine
          ports:
            - containerPort: 2049
          securityContext:
            privileged: true
          volumeMounts:
            - name: nfs-storage
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: nfs-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
