apiVersion: v2
name: prometheus-stack
description: A Helm chart for Prometheus
version: 0.1.0
dependencies:
  - name: prometheus
    version: 25.27.0
    repository: "https://prometheus-community.github.io/helm-charts"
