apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amqp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/russ/argocd-test.git
    targetRevision: HEAD
    path: amqp
  destination:
    server: https://kubernetes.default.svc
    namespace: amqp
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
