apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/russ/argocd-test.git
    targetRevision: HEAD
    path: nfs
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
