apiVersion: v1
kind: Service
metadata:
  name: video-processor-amqp-service
spec:
  selector:
    app: video-processor-amqp
  ports:
    - port: 5672
      name: amqp
      protocol: TCP
      targetPort: 5672
    - port: 15672
      name: management
      protocol: TCP
      targetPort: 15672
