apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processor-amqp
spec:
  selector:
    matchLabels:
      app: video-processor-amqp
  replicas: 1
  template:
    metadata:
      labels:
        app: video-processor-amqp
    spec:
      containers:
      - name: lavinmq
        image: cloudamqp/lavinmq
        ports:
        - containerPort: 15672
