apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processor-app
  namespace: myapp
spec:
  selector:
    matchLabels:
      app: video-processor-app
  replicas: 1
  template:
    metadata:
      labels:
        app: video-processor-app
    spec:
      containers:
      - name: app
        image: video-processor:0.1.0
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: registry-ama
