apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processor-app
spec:
  selector:
    matchLabels:
      app: video-processor-app
  replicas: 1
  template:
    metadata:
      labels:
        app: video-processor-app
    spec:
      containers:
      - name: app
        image: registry.digitalocean/ama/video-processor:0.1.0
        imagePullSecrets:
        - name: do-registry
        ports:
        - containerPort: 3000
