apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: myapp
  name: fluentd-role-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: myapp
roleRef:
  kind: Role
  name: fluentd-role
  apiGroup: rbac.authorization.k8s.io
