apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processor-postgres
spec:
  selector:
    matchLabels:
      app: video-processor-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: video-processor-postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - name: postgres
          containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: password
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - c
              - exec pg_isread -U "postgres" -h 127.0.0.1 -p 5432
            initialDelaySeconds:
            periodSeconds: 10
            timeoutSeconds: 10
            failureThresold: 3
