kind: Deployment
apiVersion: apps/v1
metadata:
  name: video-processor-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-processor-postgres
  template:
    metadata:
      labels:
        app: video-processor-postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - name: postgres
          containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRES_PASSWORD
          value: password
