apiVersion: v1
kind: Service
metadata:
  name: video-processor-app-service
spec:
  type: LoadBalancer
  selector:
    app: video-processor-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
