kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres
  namespace: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      initContainers:
        - name: pgsql-data-permission-fix
          image: busybox
          command: ["/bin/chmod", "-R", "777", "/data"]
          volumeMounts:
            - name: storage
              mountPath: /data
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - name: storage
              mountPath: "/var/lib/postgresql"
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 256Mi
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: postgres-pvc
