apiVersion: v1
kind: Pod
metadata:
  name: postgres
spec:
  containers:
    - name: postgres
      image: postgres:latest
      volumeMounts:
        - mountPath: "/var/lib/postgresql"
          name: postgres-volume
  initContainers:
    - name: pgsql-data-permission-fix
      image: busybox
      command: ["/bin/chmod", "-R", "777", "/data"]
      volumeMounts:
        - name: postgres-volume
          mountPath: /data
  volumes:
    - name: postgres-volume
      persistentVolumeClaim:
        claimName: postgres-pvc
