apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-stateful-set
  namespace: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: "my-frontend"
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: my-frontend
          image: busybox
          args:
            - sleep
            - infinity
          volumeMounts:
            - mountPath: "/data"
              name: postgres-pvc
  volumeClaimTemplates:
    - metadata:
        name: postgres-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
