kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
spec:
  storageClassName: ebs-sc
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/postgresql"
